Finding the Nth Element in an Array
NillionNetwork/nada-by-example pull request #40
Opened 2024-10-15 17:05 UTC by Sohammhatre10

# New Nada Example

- [x] I have read the [contributing docs](/NillionNetwork/nada-by-example/blob/main/CONTRIBUTING.md)
- [x] This is not a duplicate of any [existing pull request](https://github.com/NillionNetwork/nada-by-example/pulls)

## Description

This example introduces a program that helps users find the Nth largest element in a list or array of `SecretIntegers`. The program solves a common problem of selecting a specific element by size from a given dataset, while maintaining security by handling secret integers. The example is further extended to show how Nada can handle multi-dimensional arrays, adding flexibility and depth for more complex use cases.

### Changes:
- Added `nth_element_of_an_array.py` to the `src/` directory.
- Added `nth_element_of_an_array_test.yaml` to the `tests/` directory for testing various edge cases and array dimensions.
- Updated `nada-project.toml` to include this new program.

## Use Case

The target use cases for this example include:
- Retrieving the Nth largest element from a dataset, useful in sorting algorithms, competitive programming, and data analysis.
- Securely working with `SecretIntegers` to ensure privacy during computations.

## Related Issues

This pull request addresses issue https://github.com/NillionNetwork/nada-by-example/issues/17, which requested a new example for selecting the Nth element from an array.

## Optional: add your information for a Nada by Example Contributor POAP

Your Twitter: 
Your Ethereum address:

2024-10-15 17:32 UTC, jimouris requested changes

2024-10-15 17:32 UTC, jimouris commented on src/nth_element_of_an_array.py
> +    total_size = Integer(size)
why have both `size` and `total_size`?

2024-10-15 17:32 UTC, jimouris commented on src/nth_element_of_an_array.py
> +    element_3 = Integer(1)
what is `element_3`? remove this?

2024-10-15 17:32 UTC, jimouris commented on src/nth_element_of_an_array.py
> +
Can you add some comments here on what this program does? Something like:
```
'''
Given a list and a secret index n, return the element in that index without revealing n.
''' 
```

2024-10-15 17:32 UTC, jimouris commented on src/nth_element_of_an_array.py
> +        element += (number == index).if_else(list[i], Integer(0))
```suggestion
        element += (Integer(i) == index).if_else(list[i], Integer(0))
```

2024-10-15 17:32 UTC, jimouris commented on src/nth_element_of_an_array.py
> +    index = total_size - n
Shouldn't `index` be just `n`?

2024-10-16 13:40 UTC, jimouris approved these changes

2024-10-22 18:17 UTC, oceans404 approved these changes

2024-10-22 18:17 UTC, merged